version: '3.8'

services:
  ######################
  # Frontend
  #####################
  frontend:
    container_name: adamoore-net-frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./web/:/usr/local/app
  ######################
  # Postgres DB
  #####################
  adamoore-dot-net-db: 
    container_name: adamoore-dot-net-db
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      # This is the username/password postgres uses for bootstrapping, NOT the
      # password the app should use to connect.
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data
